In [1]:
import numpy as np

In [2]:
from datasets import load_dataset

ds = load_dataset("google-research-datasets/poem_sentiment")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'verse_text', 'label'],
        num_rows: 892
    })
    validation: Dataset({
        features: ['id', 'verse_text', 'label'],
        num_rows: 105
    })
    test: Dataset({
        features: ['id', 'verse_text', 'label'],
        num_rows: 104
    })
})

In [4]:
train_data = ds['train'].to_pandas()
validation_data = ds['validation'].to_pandas()
test_data = ds['test'].to_pandas()

In [5]:
train_data = train_data[['verse_text','label']]
validation_data = validation_data[['verse_text','label']]
test_data = test_data[['verse_text','label']]

In [6]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_data)
validation_dataset = Dataset.from_pandas(validation_data)
test_dataset = Dataset.from_pandas(test_data)

**Converted first to pandas to remove the id column**

**Then converted back to HuggingFace Dataset object**

In [7]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("distilbert/distilbert-base-uncased-finetuned-sst-2-english")
model = AutoModelForSequenceClassification.from_pretrained("distilbert/distilbert-base-uncased-finetuned-sst-2-english", device_map="auto",num_labels=4,
                                                           ignore_mismatched_sizes=True)

[transformers] You passed `num_labels=4` which is incompatible to the `id2label` map of length `2`.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert/distilbert-base-uncased-finetuned-sst-2-english
Key               | Status   |
------------------+----------+---------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([2]) vs model:torch.Size([4])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([2, 768]) vs model:torch.Size([4, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

In [8]:
tokenizer

BertTokenizer(name_or_path='distilbert/distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [9]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=4, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [10]:
def tokenize_function(example):
  tokenized = tokenizer(example['verse_text'], padding='max_length', truncation=True,max_length=512)
  return tokenized

In [11]:
train_tokenized = train_dataset.map(tokenize_function, batched=True)
validation_tokenized = validation_dataset.map(tokenize_function, batched=True)
test_tokenized = test_dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/892 [00:00<?, ? examples/s]

Map:   0%|          | 0/105 [00:00<?, ? examples/s]

Map:   0%|          | 0/104 [00:00<?, ? examples/s]

In [12]:
train_tokenized

Dataset({
    features: ['verse_text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 892
})

In [13]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=9)

In [14]:
#training_args

In [15]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=validation_tokenized,
)

In [16]:
trainer

In [17]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=280, training_loss=0.4252578980688538, metrics={'train_runtime': 631.7349, 'train_samples_per_second': 14.12, 'train_steps_per_second': 0.443, 'total_flos': 1181651340656640.0, 'train_loss': 0.4252578980688538, 'epoch': 10.0})

In [18]:
results = trainer.evaluate()

print(results)

{'eval_loss': 0.5013795495033264}

In [19]:
predictions = trainer.predict(test_tokenized)

In [20]:
predictions

PredictionOutput(predictions=array([[-1.1802064 , -1.3050985 ,  3.8448062 , -0.72711486],
       [-1.6624925 ,  2.5584035 , -0.96139246, -0.11462735],
       [-1.2045631 , -1.3119943 ,  3.8244534 , -0.7262084 ],
       [-0.6992522 , -1.4693418 ,  3.636322  , -0.745256  ],
       [-1.5457864 ,  1.9624156 , -0.68306893,  0.0538434 ],
       [ 2.6121213 , -1.0097307 , -1.2792978 ,  0.37024176],
       [ 3.0790138 , -0.9720913 , -1.4724371 ,  0.1783653 ],
       [-1.2661111 , -1.2827948 ,  3.6418126 , -0.5802151 ],
       [-0.33536133, -1.7101675 ,  3.8575146 , -0.7400626 ],
       [-0.6543247 , -1.6451896 ,  4.149964  , -0.8038383 ],
       [-1.6330926 ,  3.428251  , -1.3012931 , -0.63811845],
       [ 2.0727472 , -1.6094291 ,  0.5672998 , -0.05977746],
       [-0.9717825 , -1.459028  ,  4.1302047 , -0.8366759 ],
       [-0.8435567 , -1.4544243 ,  4.079381  , -0.7807097 ],
       [-0.95348114, -1.5379753 ,  3.8357205 , -0.66243976],
       [ 3.106683  , -1.1167891 , -1.1882291 ,  0.11009511],
       [-1.1985931 , -0.11863331,  0.60467255,  0.594448  ],
       [-0.40204677, -1.4381434 ,  2.8634775 , -0.33528656],
       [-0.87378025, -1.5506744 ,  3.7765076 , -0.59753793],
       [-1.2428802 , -1.1410935 ,  3.547152  , -0.6132141 ],
       [-0.68471855, -1.695158  ,  3.9359062 , -0.79451877],
       [-1.282373  , -0.7080204 ,  1.9996223 ,  0.32080907],
       [-1.4928029 , -0.9977703 ,  2.8008566 , -0.13000755],
       [-0.8000065 , -1.5931077 ,  4.175043  , -0.8978046 ],
       [ 1.9744899 , -0.6975753 , -1.5827562 ,  0.62351966],
       [ 2.4042876 , -1.6010504 ,  0.6155857 , -0.21873075],
       [-1.1400898 , -0.9184705 ,  3.1554081 , -0.5232793 ],
       [-0.5089236 , -1.7105374 ,  4.145672  , -0.93296   ],
       [ 2.9474528 , -1.0136282 , -1.4239309 ,  0.20328224],
       [ 2.7225945 , -0.82074547, -1.6222775 ,  0.3669415 ],
       [-1.6679223 ,  3.3694353 , -1.3056183 , -0.56824607],
       [-1.0539951 , -1.4598106 ,  4.1203556 , -0.88248014],
       [-1.3044434 , -1.3469317 ,  4.1023164 , -0.7954728 ],
       [-0.7922701 , -1.6554538 ,  4.257746  , -0.92289567],
       [-1.5597712 ,  1.0224626 , -0.08988693,  0.3215548 ],
       [ 3.1839736 , -1.4466063 , -0.6481832 , -0.01445334],
       [-0.44071552, -1.8078431 ,  4.0554695 , -0.8188879 ],
       [-1.1834383 , -0.52210945,  1.5828314 ,  0.03796279],
       [-0.8401518 , -1.5428772 ,  4.150628  , -0.81129164],
       [-1.6240304 ,  3.1926236 , -1.3387764 , -0.38700488],
       [ 2.6131105 , -1.4668409 , -0.33766836,  0.05389412],
       [-0.87223727, -1.4278029 ,  3.9773133 , -0.9395156 ],
       [-1.3293285 , -0.7383919 ,  2.6278422 , -0.33830842],
       [-1.8483524 ,  2.3708975 , -0.91453874,  0.05774429],
       [-1.3218149 , -0.98544514,  3.413     , -0.43733302],
       [ 0.19947389, -1.8316531 ,  3.3449976 , -0.71065295],
       [ 1.4291837 , -1.7018209 ,  1.2584327 , -0.20451117],
       [ 0.2780989 , -1.9252163 ,  3.4352715 , -0.7911223 ],
       [ 3.0051916 , -0.8487272 , -1.5905739 ,  0.2508528 ],
       [ 2.2265    , -0.63142383, -1.7557247 ,  0.52075607],
       [-1.6232926 ,  0.5117157 ,  0.33135918,  0.65211004],
       [-0.812146  , -1.4781842 ,  4.27668   , -0.98142606],
       [ 2.8964334 , -1.2090752 , -1.1921594 ,  0.263437  ],
       [-1.1039996 , -0.12701906,  1.3807098 , -0.12523383],
       [ 3.0947604 , -0.9784993 , -1.4000739 ,  0.16574901],
       [-1.1804079 , -1.3795956 ,  3.9517486 , -0.80957615],
       [-0.37023732, -1.7510604 ,  3.448838  , -0.66801006],
       [-1.210987  , -1.3960452 ,  4.188793  , -0.77143353],
       [ 0.85714704, -1.8646077 ,  3.0830107 , -0.90813583],
       [-0.6886241 , -1.6649263 ,  4.3107896 , -1.0141999 ],
       [ 1.2829336 , -1.8249185 ,  2.5328002 , -0.5504299 ],
       [-1.5500335 , -0.7756214 ,  2.652898  , -0.01522399],
       [-1.2515218 , -1.2230527 ,  3.8613877 , -0.68025094],
       [-1.1267319 , -1.394615  ,  3.966378  , -0.7544386 ],
       [ 2.7675807 , -0.95903444, -1.4532884 ,  0.35647118],
       [-1.1788088 , -1.3991956 ,  4.1162524 , -0.91863   ],
       [-0.14181872, -1.335075  ,  2.4281092 , -0.2192162 ],
       [-1.3229408 , -1.2799139 ,  3.8237584 , -0.67946583],
       [ 2.9146433 , -0.9500942 , -1.4713728 ,  0.3148425 ],
       [-0.9022282 , -1.4624507 ,  4.0643735 , -0.86317897],
       [-1.640462  ,  3.46319   , -1.3113766 , -0.7053302 ],
       [-1.0885468 , -0.9223149 ,  3.238087  , -0.5348591 ],
       [-1.0592391 , -0.91744125,  2.8116255 , -0.2557955 ],
       [-1.4952743 ,  1.1777657 , -0.10584525,  0.15692726],
       [-1.0329552 , -1.5181621 ,  4.097174  , -0.8526165 ],
       [-0.706925  , -1.5158415 ,  4.047602  , -0.71420187],
       [-1.2386615 , -0.89293206,  2.759832  , -0.14588767],
       [-1.486826  , -0.7952582 ,  3.0649805 , -0.432509  ],
       [-1.1211855 , -1.4376152 ,  3.901234  , -0.64423275],
       [-1.2314781 , -0.99200684,  2.3435214 , -0.03513461],
       [ 3.059188  , -0.95526785, -1.5190451 ,  0.23780039],
       [-0.9260343 , -1.3720729 ,  3.661939  , -0.6762734 ],
       [ 0.1058552 , -1.1363336 ,  1.2866514 ,  0.08712802],
       [-0.20965159, -1.7676506 ,  4.0935707 , -0.8740486 ],
       [ 2.982496  , -0.97826135, -1.4592603 ,  0.25919738],
       [ 1.4268457 , -1.7973765 ,  1.911059  , -0.4232496 ],
       [-1.4997001 , -0.97715694,  3.210104  , -0.22523363],
       [-0.2617909 , -1.7725055 ,  3.769181  , -0.8048913 ],
       [ 0.9546877 , -1.8831067 ,  2.3206494 , -0.49790576],
       [-1.0577946 , -1.2477028 ,  3.7428079 , -0.7072068 ],
       [-0.76373583, -1.596414  ,  4.3096833 , -0.96072143],
       [-1.2355027 , -1.1896515 ,  3.663581  , -0.5589563 ],
       [ 2.8021593 , -0.83708197, -1.6221619 ,  0.38956195],
       [-1.1277078 , -1.4388479 ,  4.202112  , -0.7553324 ],
       [-1.5103879 ,  1.6698666 , -0.8475409 ,  0.24443108],
       [-1.7059805 ,  2.7003157 , -1.0914243 , -0.1755889 ],
       [-1.2457271 , -1.2211475 ,  3.67461   , -0.6831569 ],
       [-0.3722465 , -1.6953211 ,  3.8772955 , -0.7829147 ],
       [-1.2036988 , -1.3588657 ,  4.0147815 , -0.73832214],
       [-1.412093  , -0.84382933,  2.8212938 , -0.09087888],
       [-0.8645783 , -1.5198603 ,  4.143651  , -0.99248534],
       [-1.4889065 ,  1.78552   , -0.53026545, -0.22430952],
       [-1.3004136 , -1.2307082 ,  3.94508   , -0.72533995],
       [-0.6696699 , -0.58570504,  0.61370116,  0.47575188]],
      dtype=float32), label_ids=array([2, 1, 2, 2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2, 2, 1,
       2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 1, 1, 2, 0, 2,
       2, 2, 0, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]), metrics={'test_loss': 0.42096301913261414, 'test_runtime': 1.6454, 'test_samples_per_second': 63.205, 'test_steps_per_second': 2.431})

In [21]:
predictions = trainer.predict(test_tokenized).predictions

In [22]:
predictions = np.argmax(predictions,axis=1)

In [23]:
predictions

array([2, 1, 2, 2, 1, 0, 0, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 0, 2, 2, 1,
       2, 2, 0, 2, 0, 0, 3, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2])

In [24]:
predictions.shape

(104,)

In [25]:
test_tokenized

Dataset({
    features: ['verse_text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 104
})

In [26]:
labels = test_tokenized["label"]

print(len(labels))

104

In [27]:
type(predictions)

numpy.ndarray

In [28]:
type(labels)

datasets.arrow_dataset.Column

In [29]:
y_true = np.array(labels)

In [30]:
from sklearn.metrics import accuracy_score, classification_report

In [31]:
accuracy_score(y_true,predictions)

0.875

In [32]:
print(classification_report(y_true,predictions))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87        19
           1       0.83      0.62      0.71        16
           2       0.90      0.93      0.91        69
           3       0.00      0.00      0.00         0

    accuracy                           0.88       104
   macro avg       0.65      0.61      0.63       104
weighted avg       0.88      0.88      0.88       104

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [33]:
model.save_pretrained('./fine-tuned-model')
tokenizer.save_pretrained('./fine-tuned-tokenizer')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./fine-tuned-tokenizer/tokenizer_config.json',
 './fine-tuned-tokenizer/tokenizer.json')

In [55]:
sentence = 'I leant upon a coppice gate'

In [56]:
input_ids = tokenizer(sentence,return_tensors='pt').input_ids

In [57]:
input_ids = input_ids.to("cuda")

In [58]:
model(input_ids).logits[0]

tensor([-1.1608, -1.3613,  4.0118, -0.7054], device='cuda:0',
       grad_fn=<SelectBackward0>)

0 - negative
1 - positive
2 - no impact
3 - mixed